[advisories]
unmaintained = "workspace"
unsound = "all"
ignore = []

[licenses]
confidence-threshold = 0.8
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "CDLA-Permissive-2.0",
    "Zlib",
    "Unicode-3.0",
    "Unlicense",
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND BSD-3-Clause"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
allow-wildcard-paths = true
skip = [
    { name = "getrandom" },
    { name = "windows-sys" },
    { name = "wit-bindgen" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
